# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
# https://flutter.dev/go/i18n-user-guide
arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: L10n

synthetic-package: false
output-dir: lib/l10n/generated

no-nullable-getter: true