name: flutter_localizations_ota_example
description: "Example for flutter_localizations_ota"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:

  cupertino_icons: ^1.0.8

  http: ^1.3.0

  flutter_localizations_ota:
    path: ../../flutter_localizations_ota

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_arb_translator: ^1.0.16

flutter:
  uses-material-design: true

        
    
    
                                      