name: flutter_localizations_ota
description: Over-The-Air updates for Flutter Framework localizations.
version: 0.8.0
repository: https://github.com/justprodev/flutter_localizations_ota

topics:
  - i18n

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
      sdk: flutter

  petitparser: ">=6.0.0 <7.0.0"
  yaml: ^3.0.0
  intl:
  collection:
  path_provider: ^2.1.5

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.16.6

